INSERTINTOCOURSES 'UI',4
go
SP_SELECTFROMCOURSE 'C#'
go
SP_UPDATECOURSE '2000','C#'
go
SP_SELECTFROMDEP 10
go
SP_DELETECOURSE '2003'
go
INSERTINTODEP 'BI', 'Buiness Intelligance'
go
INSERTINTODEP 'we','weeeeee' ,'2000' , '2020-12-12'
go
SP_SELECTFROMDEP 10
go
SP_UPDATEDEP 10,'ds','development system'
go
SP_UPDATEDEPMANAGER  10,1000,'10-2-2020'
go
SP_INSERTINTOINST 'Ahmeddd','Karam','Cairo','1985-2-8','karam@gmail.com','9000' , '100'
go
SP_SELECTFROMINST 'alex'
go
 SP_UPDATEINSTRACTOR 1000 ,  '',  'ali@gmail.com'
 go
 SP_DELETEINSTRUCTOR 'aas bbs'
 go
 SP_UPDATEADDRESS 1007 , 'kokooo@gmail.com'
 go
 SP_UPDATESALARY 1007, 8000
 go
 INSERTINTOTOPIC 'Geographic'
 go
 SELECTFROMTOPIC 'programming'
 go
 SP_UPDATEINTOTOPIC 6 ,'BackENd'
 go
 SP_UPDATETOPIC data , DB
 go
 SP_DELETETOPIC 1
 go
 INSERTINTOTYPE choice
 go
 SP_UPDATETYPE choiceee, choice
 go
 SELECTFROMTYPE 5
 go
 SP_DELETETYPE choice
 go
 SP_INSERTINTOSTD  'yo ',' rou' ,'alal ', 'monofya@gmAIL.COM' , '1998-02-02' ,' 50'
 go
 SP_SELECTFROMSTD alexandria 
 go
 SP_UPDATESTDADRESS 109 , cairo 
 go
 SP_UPDATESTDEMAIL 109 , 'kokooo@gmail.com'
 go
 SP_DELETESTUDENT '15000'
 go
 SP_DELETEDEPARTMENTCOURSE 'd','2001'
 go
 SP_INSERTDEPARTMENTCOURSE 20,2001
 go
 SP_SELECTALLCOURSESINDEPARTMENT '20'
 go
 SP_UPDATEDEPTCOURSESDURATION '20','2001','4 weeks'
 go
 SP_SELECTQUESTION 'lol ?'
 go
 SP_INSERTQUESTION 'what is the linked list ?','A',1,2000
 go
 SP_UBDATEQUESTIONTYPE_OR_QUESTION 'lol lol ?',2
 go
 SP_DELETEFROMQUESTION 'rss'
 go
 SP_INSERTINSCOURSES 'aa aa','C#'
 SP_INSERTINSCOURSES '1000','20005'
 go
 SP_SELECTINSCOURSE '1000'
 go
 SP_DELETEINSCOURSE 1000,2000
 go
 SP_UPDATEINSCOURSE 1002,2000,1000
 go
 SP_SELECTSTDANSWERS 101,5000
 go
 SP_SELECTEXAMQUESTION 20
 go
 SP_UPDATEEXAMQUESTION  5000 , 'here ?' , 'what is your name ?'
 go
 SP_SELECTFROMEXAM  '2008-02-02'
 go
 SP_INSERTINTOEXAM 'BD' , '9-9-1998' , 2003
 go
 SP_UPDATEXAMDATE 5004,'2010-08-10' 
 go
 SP_DELETEEXAM 5005
 go
 SP_SELECTSTUDENTRESULTS 101,'C#'
 go
 SP_SELECTSTUDENTRESULTS 101
 go







 

